In [2]:
import scipy.fft
import numpy as np
import scipy.signal
import random
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

#staviš tu load np.loadtxt() pogle 
# za FFT scipy.fff.rfft()
# rms obrisati dijelove koda

datoteka=np.loadtxt('asp1m1_sl.csv',delimiter=",", skiprows=1)

# Ne treba ponovno loadirati datoteku svaki put.
emg_dat = datoteka[:, 1]
grip_dat = datoteka[:, 2]
time_dat = datoteka[:, 0]
# Data length
dat_len = time_dat.shape[0]
display(dat_len)
# Ispis
display(time_dat)
display(emg_dat)
display(grip_dat)
# Sampling rate - median daje bolje rezultate od prosjeka
sampling_rate = 1./np.median(np.diff(time_dat[10:-10])) # iz ROS skripte
display(sampling_rate)


OSError: asp1m1_sl.csv not found.

In [ ]:
######################
# FFT treba napraviti na prozorima od 0.5s, kao što smo i u real-time-u s ROS-om radili
# Calculate window size for FFT - always round to nearest even number
fft_relative_window_size = 0.5
# Zaokružimo na najbliži cijeli broj - mora biti cijeli broj podataka pod prozorom
fft_window_size = round(fft_relative_window_size * sampling_rate)
# Parni broj točaka za FFT - 496 po mom izračunu ((990 / 2 = 495) + 1)
fft_window_size += (fft_window_size % 2)
display(f'fft_window: {fft_window_size}')
# FFT resolution
fft_resolution = sampling_rate / fft_window_size
display(f'fft_resolution: {fft_resolution}')
# Ukupan broj podataka mora biti višekratnik veličine prozora da bi obrada funkcionirala
# U real-time-u se podaci tako i obrađuju (kad ih se skupi 496)
# Reshape data to window_size × n array (disregard starting few points)
time_dat = time_dat[dat_len%fft_window_size:].reshape((-1, fft_window_size)) 
emg_dat = emg_dat[dat_len%fft_window_size:].reshape((-1, fft_window_size)) 
grip_dat = grip_dat[dat_len%fft_window_size:].reshape((-1, fft_window_size)) 
# Calculate RFFT on emg_data
emg_fft = scipy.fft.rfft(emg_dat)
# Ispis oblika matrica
display(f'time: {time_dat.shape}')
display(f'emg_dat: {emg_dat.shape}')
display(f'grip_dat: {grip_dat.shape}')
display(f'emg_fft: {emg_fft.shape}')
fft_dim = emg_fft.shape[1] # koliko je dugačak redak u fft
print (f'fft_dim: {fft_dim}')


In [3]:
# kod za sve da povleče:

import glob
import os
import pandas as pd


print('Get current working directory : ', os.getcwd()) #help function
cvs_files = glob.glob("c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\*.csv")
print(cvs_files)
array_for_output1 = []
array_for_output2 =[]
array_for_output3 =[]
array_for_output4 = []


for file in cvs_files:
    datoteka=np.loadtxt(file, delimiter=",", skiprows=1)

    emg_dat = datoteka[:, 1]
    grip_dat = datoteka[:, 2]
    time_dat = datoteka[:, 0]
    # Data length
    dat_len = time_dat.shape[0]
    display(dat_len)
    # Ispis
    display(time_dat)
    display(emg_dat)
    display(grip_dat)
    # Sampling rate - median daje bolje rezultate od prosjeka
    sampling_rate = 1./np.median(np.diff(time_dat[10:-10])) # iz ROS skripte
    display(sampling_rate)

    ######################
    # FFT treba napraviti na prozorima od 0.5s, kao što smo i u real-time-u s ROS-om radili
    # Calculate window size for FFT - always round to nearest even number
    fft_relative_window_size = 0.5
    # Zaokružimo na najbliži cijeli broj - mora biti cijeli broj podataka pod prozorom
    fft_window_size = round(fft_relative_window_size * sampling_rate)
    # Parni broj točaka za FFT - 496 po mom izračunu ((990 / 2 = 495) + 1)
    fft_window_size += (fft_window_size % 2)
    display(f'fft_window: {fft_window_size}')
    # FFT resolution
    fft_resolution = sampling_rate / fft_window_size
    display(f'fft_resolution: {fft_resolution}')
    # Ukupan broj podataka mora biti višekratnik veličine prozora da bi obrada funkcionirala
    # U real-time-u se podaci tako i obrađuju (kad ih se skupi 496)
    # Reshape data to window_size × n array (disregard starting few points)
    time_dat = time_dat[dat_len%fft_window_size:].reshape((-1, fft_window_size)) 
    emg_dat = emg_dat[dat_len%fft_window_size:].reshape((-1, fft_window_size)) 
    grip_dat = grip_dat[dat_len%fft_window_size:].reshape((-1, fft_window_size)) 
    # Calculate RFFT on emg_data
    emg_fft = scipy.fft.rfft(emg_dat)
    # Ispis oblika matrica
    display(f'time: {time_dat.shape}')
    display(f'emg_dat: {emg_dat.shape}')
    display(f'grip_dat: {grip_dat.shape}')
    display(f'emg_fft: {emg_fft.shape}')
    fft_dim = emg_fft.shape[1] # koliko je dugačak redak u fft
    print (f'fft_dim: {fft_dim}')

    import itertools
    rolling_window_relative_size = [i/100 for i in range(1, 50)]
    smoothing_factor = [i/1000 for i in range(50)]
    #display(len(rolling_window_relative_size))
    #display(len(smoothing_factor))

        
    max_corrs_lags = []
    max_corrs = []
    roll_wind_size = []
    smooth_fact = []

    i = 0
    for params in itertools.product(rolling_window_relative_size, smoothing_factor):
        i += 1
        # Random 0 - 1, 250 kom
        optimization_params = np.random.random(fft_dim)
        optimization_params = np.append(optimization_params, params)
        optimization_params[0] = 0 #uvijek nultu vrednost maknem skroz
        emg_ifft = scipy.fft.irfft(emg_fft * optimization_params[:fft_dim])
        rolling_window_size = round(optimization_params[fft_dim] * sampling_rate)
        emg_abs = np.abs(emg_ifft.ravel()) 
        window_ema = np.array([(1-optimization_params[fft_dim+1])**i for i in range(rolling_window_size)]) 
        window_ema = window_ema / window_ema.sum() 
        emg_ema = scipy.signal.fftconvolve(emg_abs, window_ema[::-1], mode='valid')
        grip_flat = grip_dat.ravel()[rolling_window_size-1:]
        emg_ema = emg_ema - emg_ema.mean()
        grip_flat = grip_flat - grip_flat.mean()
        corr_ema = scipy.signal.fftconvolve(emg_ema, grip_flat[::-1], mode='full')
        corr_ema /= (len(grip_flat) * emg_ema.std() * grip_flat.std())
        lags = scipy.signal.correlation_lags(len(emg_ema), len(grip_flat), mode='full')
        max_corr_lag_ema = lags[np.argmax(np.abs(corr_ema))]
        max_corr = np.abs(corr_ema).max()
        max_corrs_lags.append(max_corr_lag_ema)
        if max_corrs:
            if max_corr > np.max(max_corrs):
                optimal_params = optimization_params
        max_corrs.append(max_corr)
        roll_wind_size.append(params[0])
        smooth_fact.append(params[1])
    array_for_output1.append(np.max(max_corrs))
    array_for_output2.append(optimal_params[-1])
    array_for_output3.append(max_corrs_lags[0])
    array_for_output4.append(optimal_params[-2])

#print(array_for_output1)
#print(array_for_output2)
#print(array_for_output3)
#print(array_for_output4)
#np.savetxt("rez.csv", array_for_output1, header= ,delimiter=",")
#samo pandas 
df=pd.DataFrame({"Max_corrs": array_for_output1, "Rolling window size": array_for_output2, "Lagovi": array_for_output3, "Smoothing factor":array_for_output4})
df.to_csv ("Rezultati.csv", index=False)

    

Get current working directory :  c:\Users\Luka\Documents\Riteh\UMS
['c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\asp1m1_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\asp1m2_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\asp1m3_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\asp2m1_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\asp2m2_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\asp2m3_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\ibp1m1_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\ibp1m2_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\ibp1m3_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\ibp2m1_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\ibp2m2_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\ibp2m3_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\kbp1m1_sl.csv', 'c:\\Users\\Luka\\Documents\\Riteh\\UMS\\new_data\\kbp1m2_sl.

65625

array([1.67360896e+09, 1.67360896e+09, 1.67360896e+09, ...,
       1.67360903e+09, 1.67360903e+09, 1.67360903e+09])

array([3.236048, 3.235543, 3.240375, ..., 4.445672, 4.448556, 4.448845])

array([1.208014  , 1.17308655, 1.35048345, ..., 1.79372247, 1.81890393,
       1.81994877])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (132, 496)'

'emg_dat: (132, 496)'

'grip_dat: (132, 496)'

'emg_fft: (132, 249)'

fft_dim: 249


48920

array([1.67360905e+09, 1.67360905e+09, 1.67360905e+09, ...,
       1.67360910e+09, 1.67360910e+09, 1.67360910e+09])

array([3.345865, 3.345793, 3.346346, ..., 2.952994, 2.949749, 2.951408])

array([1.624087  , 1.60612736, 1.623069  , ..., 2.64974828, 2.61106383,
       2.60906063])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (98, 496)'

'emg_dat: (98, 496)'

'grip_dat: (98, 496)'

'emg_fft: (98, 249)'

fft_dim: 249


87673

array([1.67360913e+09, 1.67360913e+09, 1.67360913e+09, ...,
       1.67360922e+09, 1.67360922e+09, 1.67360922e+09])

array([2.448816, 2.445931, 2.439464, ..., 3.401399, 3.399187, 3.397817])

array([4.011983  , 3.9942563 , 4.04766068, ..., 2.22733983, 2.22774456,
       2.22814938])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (176, 496)'

'emg_dat: (176, 496)'

'grip_dat: (176, 496)'

'emg_fft: (176, 249)'

fft_dim: 249


55458

array([1.67360929e+09, 1.67360929e+09, 1.67360929e+09, ...,
       1.67360935e+09, 1.67360935e+09, 1.67360935e+09])

array([15.038223, 15.032286, 15.033319, ..., 11.188371, 11.187169,
       11.188515])

array([0.375868  , 0.39383192, 0.37661847, ..., 4.69141426, 4.65910694,
       4.645142  ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (111, 496)'

'emg_dat: (111, 496)'

'grip_dat: (111, 496)'

'emg_fft: (111, 249)'

fft_dim: 249


48944

array([1.67360936e+09, 1.67360936e+09, 1.67360936e+09, ...,
       1.67360941e+09, 1.67360941e+09, 1.67360941e+09])

array([10.40888 , 10.405058, 10.404385, ...,  8.234533,  8.23285 ,
        8.231696])

array([1.931618  , 1.94983636, 1.96704553, ..., 8.87147525, 8.86740528,
       8.86333145])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (98, 496)'

'emg_dat: (98, 496)'

'grip_dat: (98, 496)'

'emg_fft: (98, 249)'

fft_dim: 249


54303

array([1.67360946e+09, 1.67360946e+09, 1.67360946e+09, ...,
       1.67360951e+09, 1.67360951e+09, 1.67360951e+09])

array([8.104955, 8.106157, 8.105484, ..., 8.403058, 8.400245, 8.399091])

array([1.099472  , 1.117561  , 1.11806143, ..., 1.9289757 , 1.92779049,
       1.92660528])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (109, 496)'

'emg_dat: (109, 496)'

'grip_dat: (109, 496)'

'emg_fft: (109, 249)'

fft_dim: 249


33844

array([1.67092844e+09, 1.67092844e+09, 1.67092844e+09, ...,
       1.67092847e+09, 1.67092847e+09, 1.67092847e+09])

array([ 0.11854 ,  0.11842 ,  0.118227, ..., -0.455789, -0.450668,
       -0.443817])

array([-0.551216  , -0.551216  , -0.551216  , ...,  1.74306019,
        1.67663874,  1.72501325])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (68, 496)'

'emg_dat: (68, 496)'

'grip_dat: (68, 496)'

'emg_fft: (68, 249)'

fft_dim: 249


32322

array([1.67092911e+09, 1.67092911e+09, 1.67092911e+09, ...,
       1.67092915e+09, 1.67092915e+09, 1.67092915e+09])

array([2.034898, 2.02884 , 2.023527, ..., 2.220972, 2.223424, 2.229506])

array([1.499179  , 1.49942053, 1.535357  , ..., 2.457957  , 2.42327097,
       2.43925123])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (65, 496)'

'emg_dat: (65, 496)'

'grip_dat: (65, 496)'

'emg_fft: (65, 249)'

fft_dim: 249


22371

array([1.67092975e+09, 1.67092975e+09, 1.67092975e+09, ...,
       1.67092977e+09, 1.67092977e+09, 1.67092977e+09])

array([1.038091, 1.038788, 1.034413, ..., 1.252821, 1.249552, 1.250561])

array([2.823103  , 2.78681717, 2.768836  , ..., 3.51342469, 3.51799135,
       3.52255694])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (45, 496)'

'emg_dat: (45, 496)'

'grip_dat: (45, 496)'

'emg_fft: (45, 249)'

fft_dim: 249


31285

array([1.67093003e+09, 1.67093003e+09, 1.67093003e+09, ...,
       1.67093006e+09, 1.67093006e+09, 1.67093006e+09])

array([-7.640906, -7.600037, -7.567269, ..., -7.272869, -7.284553,
       -7.28061 ])

array([-0.179862  , -0.1440646 , -0.19779573, ...,  0.706559  ,
        0.70485965,  0.68847   ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (63, 496)'

'emg_dat: (63, 496)'

'grip_dat: (63, 496)'

'emg_fft: (63, 249)'

fft_dim: 249


26542

array([1.67093038e+09, 1.67093038e+09, 1.67093038e+09, ...,
       1.67093040e+09, 1.67093040e+09, 1.67093040e+09])

array([-10.223461, -10.223942, -10.220456, ..., -10.10547 , -10.092368,
       -10.084555])

array([0.507563  , 0.47151008, 0.50046882, ..., 1.18773874, 1.16952034,
       1.16633551])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (53, 496)'

'emg_dat: (53, 496)'

'grip_dat: (53, 496)'

'emg_fft: (53, 249)'

fft_dim: 249


29360

array([1.67093049e+09, 1.67093049e+09, 1.67093049e+09, ...,
       1.67093052e+09, 1.67093052e+09, 1.67093052e+09])

array([-12.922084, -12.918839, -12.915064, ..., -16.311224, -16.309517,
       -16.312811])

array([-0.903466  , -0.90419468, -0.90492337, ...,  1.82110808,
        1.78854948,  1.77036894])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (59, 496)'

'emg_dat: (59, 496)'

'grip_dat: (59, 496)'

'emg_fft: (59, 249)'

fft_dim: 249


33323

array([1.67361090e+09, 1.67361090e+09, 1.67361090e+09, ...,
       1.67361093e+09, 1.67361093e+09, 1.67361093e+09])

array([0.403759, 0.401908, 0.399312, ..., 0.89534 , 0.868199, 0.852885])

array([1.587909  , 1.56967761, 1.551723  , ..., 0.303504  , 0.26793846,
       0.267326  ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (67, 496)'

'emg_dat: (67, 496)'

'grip_dat: (67, 496)'

'emg_fft: (67, 249)'

fft_dim: 249


31113

array([1.67361097e+09, 1.67361097e+09, 1.67361097e+09, ...,
       1.67361100e+09, 1.67361100e+09, 1.67361100e+09])

array([0.259396, 0.266175, 0.269565, ..., 0.185255, 0.180735, 0.17434 ])

array([ 1.678355  ,  1.71425627,  1.67808328, ..., -0.38934456,
       -0.37112476, -0.40457039])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (62, 496)'

'emg_dat: (62, 496)'

'grip_dat: (62, 496)'

'emg_fft: (62, 249)'

fft_dim: 249


38100

array([1.67361102e+09, 1.67361102e+09, 1.67361102e+09, ...,
       1.67361106e+09, 1.67361106e+09, 1.67361106e+09])

array([-0.055391, -0.057459, -0.049285, ...,  0.230619,  0.226148,
        0.218503])

array([-0.456278  , -0.52878071, -0.546731  , ..., -0.74026179,
       -0.7396191 , -0.73897625])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (76, 496)'

'emg_dat: (76, 496)'

'grip_dat: (76, 496)'

'emg_fft: (76, 249)'

fft_dim: 249


32839

array([1.67361112e+09, 1.67361112e+09, 1.67361112e+09, ...,
       1.67361116e+09, 1.67361116e+09, 1.67361116e+09])

array([21.373459, 21.366152, 21.354755, ..., 20.838221, 20.834518,
       20.83964 ])

array([ 0.683399  ,  0.70161308,  0.72059597, ..., -0.27412851,
       -0.24140178, -0.3076403 ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (66, 496)'

'emg_dat: (66, 496)'

'grip_dat: (66, 496)'

'emg_fft: (66, 249)'

fft_dim: 249


38959

array([1.67361117e+09, 1.67361117e+09, 1.67361117e+09, ...,
       1.67361121e+09, 1.67361121e+09, 1.67361121e+09])

array([20.45624 , 20.453331, 20.461241, ..., 18.557783, 18.555017,
       18.548744])

array([ 1.370824  ,  1.388913  ,  1.38836093, ..., -0.52782314,
       -0.47635964, -0.456817  ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (78, 496)'

'emg_dat: (78, 496)'

'grip_dat: (78, 496)'

'emg_fft: (78, 249)'

fft_dim: 249


43732

array([1.67361122e+09, 1.67361122e+09, 1.67361122e+09, ...,
       1.67361126e+09, 1.67361126e+09, 1.67361126e+09])

array([18.075554, 18.067596, 18.060553, ..., 16.901463, 16.898792,
       16.886412])

array([-0.492456  , -0.52811643, -0.45704123, ...,  0.28295886,
        0.30026577,  0.26559481])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (88, 496)'

'emg_dat: (88, 496)'

'grip_dat: (88, 496)'

'emg_fft: (88, 249)'

fft_dim: 249


25045

array([1.67361150e+09, 1.67361150e+09, 1.67361150e+09, ...,
       1.67361153e+09, 1.67361153e+09, 1.67361153e+09])

array([12.836446, 12.831566, 12.826469, ..., 10.651738, 10.641809,
       10.640463])

array([ 0.158783  ,  0.10490408,  0.15928344, ..., -0.33670218,
       -0.329646  , -0.37480728])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (50, 496)'

'emg_dat: (50, 496)'

'grip_dat: (50, 496)'

'emg_fft: (50, 249)'

fft_dim: 249


25980

array([1.67361155e+09, 1.67361155e+09, 1.67361155e+09, ...,
       1.67361157e+09, 1.67361157e+09, 1.67361157e+09])

array([10.927339, 10.913178, 10.901062, ...,  9.017509,  9.020659,
        9.022991])

array([-0.221104  , -0.29309271, -0.23893853, ...,  1.66706999,
        1.62502079,  1.62729758])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (52, 496)'

'emg_dat: (52, 496)'

'grip_dat: (52, 496)'

'emg_fft: (52, 249)'

fft_dim: 249


27668

array([1.67361158e+09, 1.67361158e+09, 1.67361158e+09, ...,
       1.67361161e+09, 1.67361161e+09, 1.67361161e+09])

array([9.400428, 9.377517, 9.371627, ..., 6.2177  , 6.221402, 6.221691])

array([-0.365824  , -0.40188157, -0.38441344, ...,  1.04042612,
        1.01154092,  1.03239519])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (55, 496)'

'emg_dat: (55, 496)'

'grip_dat: (55, 496)'

'emg_fft: (55, 249)'

fft_dim: 249


21830

array([1.67361170e+09, 1.67361170e+09, 1.67361170e+09, ...,
       1.67361172e+09, 1.67361172e+09, 1.67361172e+09])

array([-1.883554, -1.884588, -1.883747, ..., -2.705284, -2.702423,
       -2.705428])

array([0.33969   , 0.4117959 , 0.37561784, ..., 0.4682025 , 0.46468774,
       0.47605659])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (44, 496)'

'emg_dat: (44, 496)'

'grip_dat: (44, 496)'

'emg_fft: (44, 249)'

fft_dim: 249


25325

array([1.67361173e+09, 1.67361173e+09, 1.67361173e+09, ...,
       1.67361175e+09, 1.67361175e+09, 1.67361175e+09])

array([-1.028937, -1.025307, -1.016243, ..., -3.219944, -3.226243,
       -3.234008])

array([0.213059  , 0.26733187, 0.26806055, ..., 0.83627977, 0.81306694,
       0.79067757])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (51, 496)'

'emg_dat: (51, 496)'

'grip_dat: (51, 496)'

'emg_fft: (51, 249)'

fft_dim: 249


23560

array([1.67361176e+09, 1.67361176e+09, 1.67361176e+09, ...,
       1.67361179e+09, 1.67361179e+09, 1.67361179e+09])

array([-0.804542, -0.824833, -0.833872, ..., -3.836704, -3.842378,
       -3.837978])

array([-0.130658  , -0.1126861 , -0.13090816, ...,  0.954751  ,
        0.954751  ,  0.954751  ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (47, 496)'

'emg_dat: (47, 496)'

'grip_dat: (47, 496)'

'emg_fft: (47, 249)'

fft_dim: 249


34264

array([1.67360574e+09, 1.67360574e+09, 1.67360574e+09, ...,
       1.67360577e+09, 1.67360577e+09, 1.67360577e+09])

array([5.591796, 5.593791, 5.597806, ..., 5.679087, 5.685506, 5.680986])

array([-0.347735  , -0.347735  , -0.34823532, ..., -0.56482   ,
       -0.58594957, -0.55824257])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (69, 496)'

'emg_dat: (69, 496)'

'grip_dat: (69, 496)'

'emg_fft: (69, 249)'

fft_dim: 249


29872

array([1.67360580e+09, 1.67360580e+09, 1.67360580e+09, ...,
       1.67360583e+09, 1.67360583e+09, 1.67360583e+09])

array([5.598047, 5.612711, 5.616486, ..., 5.138968, 5.138223, 5.138127])

array([-0.709541  , -0.709541  , -0.70898881, ...,  2.29968461,
        2.32578585,  2.329602  ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (60, 496)'

'emg_dat: (60, 496)'

'grip_dat: (60, 496)'

'emg_fft: (60, 249)'

fft_dim: 249


25795

array([1.67360593e+09, 1.67360593e+09, 1.67360593e+09, ...,
       1.67360596e+09, 1.67360596e+09, 1.67360596e+09])

array([5.088324, 5.088708, 5.086737, ..., 5.010456, 5.006081, 5.006177])

array([-0.655266  , -0.65513661, -0.63711891, ...,  4.56802596,
        4.55371522,  4.5394011 ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (52, 496)'

'emg_dat: (52, 496)'

'grip_dat: (52, 496)'

'emg_fft: (52, 249)'

fft_dim: 249


24697

array([1.67360627e+09, 1.67360627e+09, 1.67360627e+09, ...,
       1.67360631e+09, 1.67360631e+09, 1.67360631e+09])

array([-0.334189, -0.332603, -0.32842 , ..., -0.486462, -0.483289,
       -0.477279])

array([-0.673355  , -0.61883789, -0.58390965, ...,  2.75627891,
        2.74717182,  2.73806258])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (49, 496)'

'emg_dat: (49, 496)'

'grip_dat: (49, 496)'

'emg_fft: (49, 249)'

fft_dim: 249


34169

array([1.67360632e+09, 1.67360632e+09, 1.67360632e+09, ...,
       1.67360636e+09, 1.67360636e+09, 1.67360636e+09])

array([-0.506392, -0.506392, -0.507425, ..., -0.29457 , -0.312072,
       -0.312793])

array([-0.492456  , -0.49217134, -0.45654966, ...,  2.65240148,
        2.64637063,  2.64034548])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (68, 496)'

'emg_dat: (68, 496)'

'grip_dat: (68, 496)'

'emg_fft: (68, 249)'

fft_dim: 249


33776

array([1.67360636e+09, 1.67360636e+09, 1.67360636e+09, ...,
       1.67360640e+09, 1.67360640e+09, 1.67360640e+09])

array([-0.824881, -0.831901, -0.836853, ..., -0.720304, -0.72343 ,
       -0.72843 ])

array([-0.56482   , -0.510545  , -0.51105405, ...,  3.01612812,
        2.99988778,  2.98364744])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (68, 496)'

'emg_dat: (68, 496)'

'grip_dat: (68, 496)'

'emg_fft: (68, 249)'

fft_dim: 249


31670

array([1.67092521e+09, 1.67092521e+09, 1.67092521e+09, ...,
       1.67092524e+09, 1.67092524e+09, 1.67092524e+09])

array([3.457826, 3.451984, 3.45333 , ..., 3.722512, 3.718281, 3.706309])

array([-0.959628  , -1.05021136, -1.068171  , ...,  0.17712838,
        0.17257469,  0.16801993])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (63, 496)'

'emg_dat: (63, 496)'

'grip_dat: (63, 496)'

'emg_fft: (63, 249)'

fft_dim: 249


33327

array([1.67092578e+09, 1.67092578e+09, 1.67092578e+09, ...,
       1.67092581e+09, 1.67092581e+09, 1.67092581e+09])

array([3.476906, 3.496259, 3.515972, ..., 3.350309, 3.323888, 3.313551])

array([-0.543555  , -0.57936634, -0.525466  , ..., -0.05171005,
       -0.00212704, -0.01616181])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (67, 496)'

'emg_dat: (67, 496)'

'grip_dat: (67, 496)'

'emg_fft: (67, 249)'

fft_dim: 249


27676

array([1.67092617e+09, 1.67092617e+09, 1.67092617e+09, ...,
       1.67092620e+09, 1.67092620e+09, 1.67092620e+09])

array([7.321878, 7.320821, 7.318489, ..., 7.212903, 7.213119, 7.210066])

array([-0.869183  , -0.83287987, -0.81567134, ...,  0.957919  ,
        0.957919  ,  0.957919  ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (55, 496)'

'emg_dat: (55, 496)'

'grip_dat: (55, 496)'

'emg_fft: (55, 249)'

fft_dim: 249


32340

array([1.67092652e+09, 1.67092652e+09, 1.67092652e+09, ...,
       1.67092655e+09, 1.67092655e+09, 1.67092655e+09])

array([33.66291 , 33.667404, 33.671757, ..., 34.26878 , 34.266975,
       34.26498 ])

array([-0.254114  , -0.2540062 , -0.23552468, ...,  1.68950844,
        1.70773183,  1.70121173])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (65, 496)'

'emg_dat: (65, 496)'

'grip_dat: (65, 496)'

'emg_fft: (65, 249)'

fft_dim: 249


31501

array([1.67360684e+09, 1.67360684e+09, 1.67360684e+09, ...,
       1.67360687e+09, 1.67360687e+09, 1.67360687e+09])

array([ 0.566297,  0.564398,  0.557378, ..., -0.017263, -0.015388,
       -0.013729])

array([-0.546731  , -0.60074884, -0.56532033, ...,  0.95763415,
        0.95374135,  0.94984761])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (63, 496)'

'emg_dat: (63, 496)'

'grip_dat: (63, 496)'

'emg_fft: (63, 249)'

fft_dim: 249


32326

array([1.67092798e+09, 1.67092798e+09, 1.67092798e+09, ...,
       1.67092801e+09, 1.67092801e+09, 1.67092801e+09])

array([26.571022, 26.573547, 26.571239, ..., 27.203217, 27.200933,
       27.210356])

array([-1.075823  , -1.03990378, -1.075823  , ...,  0.13379886,
        0.11812   ,  0.11812   ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (65, 496)'

'emg_dat: (65, 496)'

'grip_dat: (65, 496)'

'emg_fft: (65, 249)'

fft_dim: 249


32796

array([1.67360820e+09, 1.67360820e+09, 1.67360820e+09, ...,
       1.67360823e+09, 1.67360823e+09, 1.67360823e+09])

array([-5.280291, -5.297215, -5.308634, ..., -6.768833, -6.767198,
       -6.754   ])

array([ 0.773852  ,  0.77397708,  0.79119053, ..., -0.11292334,
       -0.166836  , -0.166836  ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (66, 496)'

'emg_dat: (66, 496)'

'grip_dat: (66, 496)'

'emg_fft: (66, 249)'

fft_dim: 249


38084

array([1.67360824e+09, 1.67360824e+09, 1.67360824e+09, ...,
       1.67360828e+09, 1.67360828e+09, 1.67360828e+09])

array([-7.304288, -7.314601, -7.320852, ..., -7.670329, -7.664391,
       -7.652491])

array([0.430135  , 0.3762303 , 0.42988484, ..., 0.285415  , 0.28281422,
       0.26459648])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (76, 496)'

'emg_dat: (76, 496)'

'grip_dat: (76, 496)'

'emg_fft: (76, 249)'

fft_dim: 249


47806

array([1.67360829e+09, 1.67360829e+09, 1.67360829e+09, ...,
       1.67360834e+09, 1.67360834e+09, 1.67360834e+09])

array([-7.888858, -7.882823, -7.874914, ..., -6.989814, -6.987938,
       -6.985582])

array([4.265246  , 4.22917152, 4.24785738, ..., 1.03964114, 1.00101365,
       0.98279218])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (96, 496)'

'emg_dat: (96, 496)'

'grip_dat: (96, 496)'

'emg_fft: (96, 249)'

fft_dim: 249


35690

array([1.67360842e+09, 1.67360842e+09, 1.67360842e+09, ...,
       1.67360846e+09, 1.67360846e+09, 1.67360846e+09])

array([14.488488, 14.488681, 14.495484, ..., 12.635371, 12.606835,
       12.581953])

array([4.482323  , 4.482323  , 4.48308654, ..., 3.39992167, 3.38862645,
       3.36549218])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (71, 496)'

'emg_dat: (71, 496)'

'grip_dat: (71, 496)'

'emg_fft: (71, 249)'

fft_dim: 249


40521

array([1.67360847e+09, 1.67360847e+09, 1.67360847e+09, ...,
       1.67360851e+09, 1.67360851e+09, 1.67360851e+09])

array([11.47753 , 11.466184, 11.47128 , ..., 10.230885, 10.230066,
       10.231462])

array([1.262282  , 1.20827272, 1.24342859, ..., 1.98567132, 2.03556337,
       2.03151662])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (81, 496)'

'emg_dat: (81, 496)'

'grip_dat: (81, 496)'

'emg_fft: (81, 249)'

fft_dim: 249


42761

array([1.67360852e+09, 1.67360852e+09, 1.67360852e+09, ...,
       1.67360856e+09, 1.67360856e+09, 1.67360856e+09])

array([9.193462, 9.20344 , 9.197044, ..., 5.489175, 5.479872, 5.470592])

array([1.4251    , 1.42465999, 1.37109997, ..., 1.859262  , 1.86212588,
       1.89699665])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (86, 496)'

'emg_dat: (86, 496)'

'grip_dat: (86, 496)'

'emg_fft: (86, 249)'

fft_dim: 249


28772

array([1.67360748e+09, 1.67360748e+09, 1.67360748e+09, ...,
       1.67360751e+09, 1.67360751e+09, 1.67360751e+09])

array([3.155584, 3.154526, 3.150295, ..., 2.834715, 2.833753, 2.831397])

array([0.538678  , 0.55701698, 0.59320871, ..., 0.95382712, 0.93879924,
       0.97166281])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (58, 496)'

'emg_dat: (58, 496)'

'grip_dat: (58, 496)'

'emg_fft: (58, 249)'

fft_dim: 249


42931

array([1.67360753e+09, 1.67360753e+09, 1.67360753e+09, ...,
       1.67360758e+09, 1.67360758e+09, 1.67360758e+09])

array([2.36554 , 2.364458, 2.361693, ..., 2.090276, 2.093978, 2.091862])

array([3.722542  , 3.776809  , 3.776809  , ..., 2.73051457, 2.75814973,
       2.77917459])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (86, 496)'

'emg_dat: (86, 496)'

'grip_dat: (86, 496)'

'emg_fft: (86, 249)'

fft_dim: 249


25849

array([1.67360792e+09, 1.67360792e+09, 1.67360792e+09, ...,
       1.67360794e+09, 1.67360794e+09, 1.67360794e+09])

array([-30.400133, -30.410278, -30.408188, ..., -31.66094 , -31.662142,
       -31.675028])

array([8.950584  , 8.91478115, 8.96917443, ..., 4.43077962, 4.45213585,
       4.42170006])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (52, 496)'

'emg_dat: (52, 496)'

'grip_dat: (52, 496)'

'emg_fft: (52, 249)'

fft_dim: 249


32616

array([1.67360772e+09, 1.67360772e+09, 1.67360772e+09, ...,
       1.67360776e+09, 1.67360776e+09, 1.67360776e+09])

array([43.948563, 43.937721, 43.932358, ..., 43.6758  , 43.67794 ,
       43.688419])

array([0.068338  , 0.0504903 , 0.08596074, ..., 2.29112294, 2.293424  ,
       2.27740096])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (65, 496)'

'emg_dat: (65, 496)'

'grip_dat: (65, 496)'

'emg_fft: (65, 249)'

fft_dim: 249


33168

array([1.67360777e+09, 1.67360777e+09, 1.67360777e+09, ...,
       1.67360780e+09, 1.67360780e+09, 1.67360780e+09])

array([42.277287, 42.271015, 42.270535, ..., 42.435619, 42.43615 ,
       42.437229])

array([4.391878  , 4.391878  , 4.391878  , ..., 1.57292898, 1.5396046 ,
       1.59457574])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (66, 496)'

'emg_dat: (66, 496)'

'grip_dat: (66, 496)'

'emg_fft: (66, 249)'

fft_dim: 249


38032

array([1.67360782e+09, 1.67360782e+09, 1.67360782e+09, ...,
       1.67360786e+09, 1.67360786e+09, 1.67360786e+09])

array([42.626621, 42.630085, 42.634819, ..., 42.922344, 42.920807,
       42.923161])

array([-1.270335  , -1.23414949, -1.23305629, ...,  1.09943319,
        1.08122342,  1.06387195])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (76, 496)'

'emg_dat: (76, 496)'

'grip_dat: (76, 496)'

'emg_fft: (76, 249)'

fft_dim: 249


28089

array([1.67361206e+09, 1.67361206e+09, 1.67361206e+09, ...,
       1.67361209e+09, 1.67361209e+09, 1.67361209e+09])

array([-8.560021, -8.578004, -8.588943, ..., -5.361139, -5.361788,
       -5.363399])

array([4.011983  , 4.01237108, 4.06622958, ..., 0.41897278, 0.38946817,
       0.38728037])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (56, 496)'

'emg_dat: (56, 496)'

'grip_dat: (56, 496)'

'emg_fft: (56, 249)'

fft_dim: 249


28490

array([1.67361210e+09, 1.67361210e+09, 1.67361210e+09, ...,
       1.67361213e+09, 1.67361213e+09, 1.67361213e+09])

array([-5.600871, -5.596303, -5.588418, ..., -1.195033, -1.200683,
       -1.201452])

array([-0.022116  , -0.02185728,  0.01351855, ...,  0.53377741,
        0.53146225,  0.52914654])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (57, 496)'

'emg_dat: (57, 496)'

'grip_dat: (57, 496)'

'emg_fft: (57, 249)'

fft_dim: 249


29099

array([1.67361216e+09, 1.67361216e+09, 1.67361216e+09, ...,
       1.67361219e+09, 1.67361219e+09, 1.67361219e+09])

array([-3.703471, -3.696331, -3.704072, ..., -1.987265, -1.981568,
       -1.987433])

array([2.130614  , 2.07646408, 2.09493693, ..., 0.58053162, 0.57957282,
       0.57861379])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (58, 496)'

'emg_dat: (58, 496)'

'grip_dat: (58, 496)'

'emg_fft: (58, 249)'

fft_dim: 249


27373

array([1.67361226e+09, 1.67361226e+09, 1.67361226e+09, ...,
       1.67361229e+09, 1.67361229e+09, 1.67361229e+09])

array([2.737711, 2.737783, 2.7336  , ..., 1.21758 , 1.213902, 1.214551])

array([0.556767  , 0.50275878, 0.53840196, ..., 0.61878455, 0.62240371,
       0.62602202])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (55, 496)'

'emg_dat: (55, 496)'

'grip_dat: (55, 496)'

'emg_fft: (55, 249)'

fft_dim: 249


31318

array([1.67361232e+09, 1.67361232e+09, 1.67361232e+09, ...,
       1.67361236e+09, 1.67361236e+09, 1.67361236e+09])

array([2.079794, 2.080154, 2.077919, ..., 2.304332, 2.305775, 2.311112])

array([1.316557  , 1.28066435, 1.31601408, ..., 0.18046925, 0.1784224 ,
       0.18584929])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (63, 496)'

'emg_dat: (63, 496)'

'grip_dat: (63, 496)'

'emg_fft: (63, 249)'

fft_dim: 249


28940

array([1.67361237e+09, 1.67361237e+09, 1.67361237e+09, ...,
       1.67361240e+09, 1.67361240e+09, 1.67361240e+09])

array([2.124461, 2.122802, 2.124293, ..., 1.039343, 1.043574, 1.041218])

array([0.285415  , 0.267326  , 0.26707584, ..., 0.77303671, 0.73796722,
       0.77380887])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (58, 496)'

'emg_dat: (58, 496)'

'grip_dat: (58, 496)'

'emg_fft: (58, 249)'

fft_dim: 249


55362

array([1.67360979e+09, 1.67360979e+09, 1.67360979e+09, ...,
       1.67360985e+09, 1.67360985e+09, 1.67360985e+09])

array([16.94935 , 16.955288, 16.951345, ..., 16.634348, 16.630453,
       16.631029])

array([0.538678  , 0.55647378, 0.52112382, ..., 0.33969   , 0.33969   ,
       0.33969   ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (111, 496)'

'emg_dat: (111, 496)'

'grip_dat: (111, 496)'

'emg_fft: (111, 249)'

fft_dim: 249


50119

array([1.67360986e+09, 1.67360986e+09, 1.67360986e+09, ...,
       1.67360992e+09, 1.67360992e+09, 1.67360992e+09])

array([16.182362, 16.185173, 16.185223, ..., 15.232375, 15.236534,
       15.234587])

array([0.050249  , 0.10464108, 0.122605  , ..., 1.28822425, 1.27000917,
       1.27277138])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (101, 496)'

'emg_dat: (101, 496)'

'grip_dat: (101, 496)'

'emg_fft: (101, 249)'

fft_dim: 249


56973

array([1.67360996e+09, 1.67360996e+09, 1.67360996e+09, ...,
       1.67361002e+09, 1.67361002e+09, 1.67361002e+09])

array([16.14315 , 16.143415, 16.150339, ..., 14.306694, 14.302486,
       14.300251])

array([ 1.117561  ,  1.09995512,  1.17158584, ..., -0.402011  ,
       -0.45410421, -0.47376763])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (114, 496)'

'emg_dat: (114, 496)'

'grip_dat: (114, 496)'

'emg_fft: (114, 249)'

fft_dim: 249


39717

array([1.67361010e+09, 1.67361010e+09, 1.67361010e+09, ...,
       1.67361015e+09, 1.67361015e+09, 1.67361015e+09])

array([12.266541, 12.268056, 12.26582 , ..., 12.067654, 12.063784,
       12.057557])

array([0.267326  , 0.33964831, 0.33357584, ..., 1.35226919, 1.3340508 ,
       1.3172816 ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (80, 496)'

'emg_dat: (80, 496)'

'grip_dat: (80, 496)'

'emg_fft: (80, 249)'

fft_dim: 249


56167

array([1.67361016e+09, 1.67361016e+09, 1.67361016e+09, ...,
       1.67361022e+09, 1.67361022e+09, 1.67361022e+09])

array([11.127404, 11.130626, 11.132717, ...,  8.807444,  8.811193,
        8.807756])

array([-0.311557  , -0.36557384, -0.32990047, ..., -0.4201    ,
       -0.40342154, -0.3754292 ])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (113, 496)'

'emg_dat: (113, 496)'

'grip_dat: (113, 496)'

'emg_fft: (113, 249)'

fft_dim: 249


64918

array([1.67361024e+09, 1.67361024e+09, 1.67361024e+09, ...,
       1.67361030e+09, 1.67361030e+09, 1.67361030e+09])

array([6.982141, 6.98844 , 6.990892, ..., 5.29964 , 5.319257, 5.266584])

array([-0.438189  , -0.45640308, -0.474367  , ..., -1.43551223,
       -1.4367003 , -1.43788809])

992.969696969697

'fft_window: 496'

'fft_resolution: 2.0019550342130987'

'time: (130, 496)'

'emg_dat: (130, 496)'

'grip_dat: (130, 496)'

'emg_fft: (130, 249)'

fft_dim: 249


In [ ]:
import itertools
rolling_window_relative_size = [i/100 for i in range(1, 50)]
smoothing_factor = [i/1000 for i in range(50)]
#display(len(rolling_window_relative_size))
#display(len(smoothing_factor))

      
max_corrs_lags = []
max_corrs = []
roll_wind_size = []
smooth_fact = []

i = 0
for params in itertools.product(rolling_window_relative_size, smoothing_factor):
  i += 1
  # Random 0 - 1, 250 kom
  optimization_params = np.random.random(fft_dim)
  optimization_params = np.append(optimization_params, params)
  optimization_params[0] = 0 #uvijek nultu vrednost maknem skroz
  emg_ifft = scipy.fft.irfft(emg_fft * optimization_params[:fft_dim])
  rolling_window_size = round(optimization_params[fft_dim] * sampling_rate)
  emg_abs = np.abs(emg_ifft.ravel()) 
  window_ema = np.array([(1-optimization_params[fft_dim+1])**i for i in range(rolling_window_size)]) 
  window_ema = window_ema / window_ema.sum() 
  emg_ema = scipy.signal.fftconvolve(emg_abs, window_ema[::-1], mode='valid')
  grip_flat = grip_dat.ravel()[rolling_window_size-1:]
  emg_ema = emg_ema - emg_ema.mean()
  grip_flat = grip_flat - grip_flat.mean()
  corr_ema = scipy.signal.fftconvolve(emg_ema, grip_flat[::-1], mode='full')
  corr_ema /= (len(grip_flat) * emg_ema.std() * grip_flat.std())
  lags = scipy.signal.correlation_lags(len(emg_ema), len(grip_flat), mode='full')
  max_corr_lag_ema = lags[np.argmax(np.abs(corr_ema))]
  max_corr = np.abs(corr_ema).max()
  max_corrs_lags.append(max_corr_lag_ema)
  if max_corrs:
    if max_corr > np.max(max_corrs):
      optimal_params = optimization_params
  max_corrs.append(max_corr)
  roll_wind_size.append(params[0])
  smooth_fact.append(params[1])
  # if i < 5:
  #   display(optimization_params)



In [ ]:
display(f'Max correlation: {np.max(max_corrs)}')
display(f'Lag at amx corr: {max_corrs_lags[np.argmax(max_corrs)]/sampling_rate}')
display(f'Optimal rolling_window_relative_size: {optimal_params[-2]}')
display(f'Optimal smoothing factor: {optimal_params[-1]}')

sns.set_theme(context='paper', style='whitegrid', rc={})
sns.despine()

fig, ax = plt.subplots(3, 1)
fig.set_size_inches(w=6., h=6.)
sns.scatterplot(
  x=smooth_fact,
  y=max_corrs,
  size=2.,
  legend=None,
  ax=ax[0]
)
ax[0].set_title('Correlation - Smoothing factor', fontsize='small', fontweight='bold')
sns.scatterplot(
  x=roll_wind_size,
  y=max_corrs,
  size=2.,
  legend=None,
  ax=ax[1]
)
ax[1].set_title('Correlation - Rolling window size', fontsize='small', fontweight='bold')
sns.scatterplot(
  x=max_corrs_lags/sampling_rate,
  y=max_corrs,
  size=2.,
  legend=None,
  ax=ax[2]
)
ax[2].set_title('Correlation - Time lag', fontsize='small', fontweight='bold')
# plt.plot(max_corrs_lags, max_corrs, 'o', size=2.)
# plt.grid(which='both')
plt.suptitle(t=r'Parameter optimization', fontsize='small')
plt.tight_layout()
fig.savefig('optimizacija.png', dpi=320)
plt.show()


In [ ]:
# Attenuation/amplification of single frequencies
# mijenajati FFT frekvencije množeći s vrijednostima [0, 1.5 - pojačanje]
# Kod vas je malo manji sampling rate pa umjesto 250 ima 249 frekvencija
# optimization_params = np.random.random(250)
# optimization_params = np.random.random(fft_dim)
# EMA relative window size -  u sekundama + ovaj random.random zapravo svaki 
# put kad pokrenete kod malo poveća/smanji rolling window jer ga pomnoži s
# random u rasponu (0, 1)
# rolling_window_relative_size = 0.25*random.random()
# optimization_params = np.append(optimization_params, rolling_window_relative_size)
# EMA smoothing factor - isto potebno optimirati, svaki put je malo drugačiji faktor
# zbog množenja
# smoothing_factor = 0.025 * random.random()
# optimization_params = np.append(optimization_params, smoothing_factor)
# DC offset always removed
# optimization_params[0] = 0 #uvijek nultu vrednost maknem skroz

# Optimal parameters after loop
optimization_params = optimal_params

# emg_fft se pomnoži s nekim brojevima [0, 1.5] da se zapravo filtrira signal
# i onda ide inverz da se rekonstruira početni signal + nekakvo filtriranje
emg_ifft = scipy.fft.irfft(emg_fft * optimization_params[:fft_dim])

# emg_ifft = scipy.fft.irfft (np.dot(emg_fft[:,None],optimization_params[None,:fft_dim]))
display(f'emg_ifft: {emg_ifft.shape}')
# Odredi se duljina prozora za EMA pomoću relativne duljine (u sekundama) i sampling
# rate-a
rolling_window_size = round(optimization_params[fft_dim] * sampling_rate)
# Ako je slučajno više od prozora za fft, zaokruži se na tu veličinu
display(f'rolling_window_size: {rolling_window_size}')
if rolling_window_size > fft_window_size:
  rolling_window_size  = fft_window_size

# Apsolutna vrijednost emg signala nakon filtriranja
# Ravel ga spljošti u 1D signal (spoji sve retke matrice u jedan)
emg_abs = np.abs(emg_ifft.ravel()) 
# EMA window - težine s kojima se množi signal
window_ema = np.array([(1-optimization_params[fft_dim+1])**i for i in range(rolling_window_size)]) 
# Normalizacija težina pomoću sume (suma svih težina = 1)
window_ema = window_ema / window_ema.sum() 
# EMA zaglađen emg signal (filtriranje + apsolutna + zaglađivanje)
emg_ema = scipy.signal.fftconvolve(emg_abs, window_ema[::-1], mode='valid')

# Plot
plt.figure(figsize=(8, 6), dpi=320)
plt.subplot(4, 1, 1)
# Original input signal
plt.plot(time_dat.ravel(), emg_dat.ravel())
plt.grid(which='both')
plt.subplot(4, 1, 2)
# Nakon filtriranja + rekostrukcije
plt.plot(time_dat.ravel(), emg_ifft.ravel())
plt.grid(which='both')
plt.subplot(4, 1, 3)
# Nakon apsolutne vrijednosti + zaglađivanja
plt.plot(time_dat.ravel()[rolling_window_size-1:], emg_ema)
plt.grid(which='both')
plt.subplot(4, 1, 4)
# Grip za usporedbu
plt.plot(time_dat.ravel()[rolling_window_size-1:], grip_dat.ravel()[rolling_window_size-1:])
plt.grid(which='both')
plt.show()

In [ ]:
# Vi zapravo optimirate ovih prvih 249 vrijednosti + jedna za rolling window size + jedna za smoothing factor
# Možete napraviti petlju ili nešto slično da ih pretražuje
display(optimization_params[:fft_dim].shape)
display(optimization_params[fft_dim])
display(optimization_params[fft_dim+1])

In [ ]:
display(time_dat.ravel()[rolling_window_size-1:].shape)
display(emg_ema.shape)
display(grip_dat.ravel()[rolling_window_size-1:].shape)

Cross-correlation with Pearson r

In [ ]:
grip_flat = grip_dat.ravel()[rolling_window_size-1:]
# Demean signals for 
emg_ema = emg_ema - emg_ema.mean()
grip_flat = grip_flat - grip_flat.mean()


In [ ]:

# corr_ema = scipy.signal.correlate(emg_ema, grip_flat, method='fft', mode='full')
# display(corr_ema)
corr_ema = scipy.signal.fftconvolve(emg_ema, grip_flat[::-1], mode='full')
corr_ema /= (len(grip_flat) * emg_ema.std() * grip_flat.std())
# display(corr_ema)
lags = scipy.signal.correlation_lags(len(emg_ema), len(grip_flat), mode='full')
print(f'EMA - GRIP:')
print(scipy.stats.pearsonr(emg_ema, grip_flat)[0])
max_corr_lag_ema = lags[np.argmax(np.abs(corr_ema))]
print(f'EMA -> Corr at 0 lag: {corr_ema[lags == 0]}')
print(f'EMA -> Max corr: {np.abs(corr_ema).max()}, Lag: {max_corr_lag_ema} or {max_corr_lag_ema/sampling_rate} sec')
plt.figure(figsize=(8, 6), dpi=320)
plt.plot(lags, corr_ema)
plt.legend(['EMA - GRIP'])
plt.grid(which='both')
plt.show()

In [ ]:
# %timeit corr_ema = scipy.signal.correlate(emg_ema, grip_flat, method='fft', mode='full')
corr_ema1 = scipy.signal.correlate(emg_ema, grip_flat, method='fft', mode='full')
display(corr_ema)
# %timeit corr_ema = scipy.signal.fftconvolve(emg_ema, grip_flat[::-1], mode='full')
corr_ema2 = scipy.signal.fftconvolve(emg_ema, grip_flat[::-1], mode='full')
display(corr_ema)
# %timeit corr_ema = np.convolve(emg_ema, grip_flat[::-1])
corr_ema3 = np.convolve(emg_ema, grip_flat[::-1])
display(corr_ema)
# %timeit corr_ema = np.correlate(emg_ema, grip_flat, mode='full')
corr_ema4 = np.correlate(emg_ema, grip_flat, mode='full')
np.allclose(corr_ema1, corr_ema4)

In [ ]:
"""
import numba as nb
def rolling_window(emg_arr, window_size):
  shape = emg_arr.shape[:-1] + (emg_arr.shape[-1] - window_size + 1, window_size)
  strides = emg_arr.strides + (emg_arr.strides[-1],)
  return np.lib.stride_tricks.as_strided(emg_arr, shape=shape, strides=strides)


@nb.jit(nb.float64[:,:](nb.float64[:], nb.int64), nopython=True)
def rolling_window_nb(emg_arr, window_size):
  shape = emg_arr.shape[:-1] + (emg_arr.shape[-1] - window_size + 1, window_size)
  strides = emg_arr.strides + (emg_arr.strides[-1],)
  return np.lib.stride_tricks.as_strided(emg_arr, shape=shape, strides=strides)
  """

In [ ]:
"""
%timeit rolling_window_nb(grip, 500)
%timeit rolling_window(grip, 500)
"""

In [ ]:
"""
def exponential_ma(emg_rolling, decay, window_size):
  # ema_decay = 0.005
  window_ema = np.array([(1-decay)**i for i in range(window_size)])
  window_ema = window_ema / window_ema.sum()
  emg_abs = np.abs(emg_rolling)
  return scipy.signal.fftconvolve(emg_abs, window_ema[::-1], mode='valid')
  return np.average(np.abs(emg_rolling), axis=-1, weights=window_ema)

@nb.jit(nb.float64[:](nb.float64[:,:], nb.float64, nb.int64), nopython=True, fastmath=True)
def exponential_ma_nb(emg_rolling, decay, window_size):
  # ema_decay = 0.005
  window_ema = np.array([(1-decay)**i for i in range(window_size)])
  window_ema = window_ema / np.sum(window_ema)
  emg_abs = np.abs(emg_rolling)
  emg_ema = np.sum(emg_abs*window_ema, axis=-1)
  return emg_ema
  """

In [ ]:
"""
%timeit exponential_ma(b.ravel(), 0.005, window_size)
%timeit exponential_ma_nb(windowed_emg, 0.005, window_size)
"""

In [ ]:
"""
exponential_ma_nb(windowed_emg, 0.005, fft_window_size)
# scipy.signal.fftconvolve(np.abs(b.flat), window_ma[::-1], mode='valid')
# b
# windowed_emg
"""

In [ ]:
"""
np.all(np.isclose(
  exponential_ma(b.flat, 0.005, fft_window_size),
  exponential_ma_nb(windowed_emg, 0.005, fft_window_size)
  ))
# np.all(np.isclose(
#   exponential_ma(b.flat, 0.005, window_size), 
#   scipy.signal.fftconvolve(np.abs(b.flat), window_ma[::-1], mode='valid'),
#   ))
"""